### ISSUE TITLE
Must use HTTPS with Pypi

### ISSUE THREAD

**Issue by jdkx** [mardiros/pyshop#68]
For two days now my Pyshop setup has failed to contact Pypi. 

This is the error every time:

```
  File "/home/pyshop/prod/local/lib/python2.7/site-packages/pyshop/helpers/pypi.py", line 66, in request
    str(e), resp.headers)
ProtocolError: <ProtocolError for http://pypi.python.org/pypi: 403 403 Client Error: Must access using HTTPS instead of HTTP>
```

Suggested fix: `use_https = True` in `RequestsTransport`. It works and it would fix the problem for everyone who mirrors Pypi directly (it could be an issue for users who mirror a non-SSL aware server).

**Comment by sam-at-github** [comment]
@jdkx  Can you please be a bit more specific? Where/what is `RequestsTransport`

**Comment by ida** [comment]
Had this error with another package, resolved that error by upgrading setuptools, but still uploads didn't happen. Finally using [twine](https://pypi.python.org/pypi/twine/) worked.

**Comment by mardiros** [comment]
@jdkx 

PyShop sample configuration is using https since a long time.

https://github.com/mardiros/pyshop/blob/master/pyshop.sample.ini#L41

Are you using https ?

RequestTransport is defined here:

https://github.com/mardiros/pyshop/blob/master/pyshop/helpers/pypi.py#L34

Because the standard library of python does not check TLS Certificate, pyshop define
its own "transport" to ensure https is secure.

defined here:

https://github.com/mardiros/pyshop/blob/master/pyshop/helpers/pypi.py#L34

The `use_https` is compute with the setting `pyshop.pypi.url`
